name: widget_zoom_pro
description: A widget to zoom another widget either directly in an overlay or in fullscreen.
version: 0.0.6
homepage: https://github.com/Koleshy/widget_zoom_pro
repository: https://github.com/Koleshy/widget_zoom_pro

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: